name: CI/CD Pipeline for WebLogic Deployment

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to main branch

jobs:
  build:
    runs-on:
      - self-hosted
      - linux
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build WAR file
        run: |
          mvn clean package -DskipTests

  deploy:
    runs-on:
      - self-hosted
      - linux
    needs: build  # Make sure deploy runs after build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy WAR file to WebLogic
        run: |
          chmod +x ./deploy_to_weblogic.sh
          ./deploy_to_weblogic.sh  # Run your deploy script
