name: CI/CD Pipeline for WebLogic Deployment

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to main branch

jobs:
  build:
    runs-on: [self-hosted, linux]  # Run on your self-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Ensure JDK 11 is used (Oracle JDK or OpenJDK)

    - name: Set up Maven
      uses: actions/setup-maven@v2

    - name: Build WAR file
      run: |
        mvn clean package -DskipTests  # Builds the WAR file

  deploy:
    runs-on: [self-hosted, linux]  # Run on your self-hosted runner
    needs: build  # Wait for the build job to finish first

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy WAR file to WebLogic
      run: |
        chmod +x ./deploy_to_weblogic.sh
        ./deploy_to_weblogic.sh  # Run your deploy script
